version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27015:27017'
    volumes:
      - ./mongodb_data:/data/db
      - ./collections:/docker-entrypoint-initdb.d

  mongo-seed:
    build:
      # context: ./mongo-seed
      dockerfile: Dockerfile
    depends_on:
      - mongodb
volumes:
  mongodb_data:
